In [5]:
import numpy as np

python_list = [1, 2, 3, 4, 5]
array_from_list = np.array(python_list)
print("Массив из списка:", array_from_list)

nested_list = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(nested_list)
print("Двумерный массив:")
print(array_2d)

zeros_array = np.zeros(5)
print("Массив из нулей:", zeros_array)

ones_array_2d = np.ones((3, 4))
print("Массив 3x4 из единиц:")
print(ones_array_2d)

range_array = np.arange(0, 10, 2)
print("Массив с arange:", range_array)

Массив из списка: [1 2 3 4 5]
Двумерный массив:
[[1 2 3]
 [4 5 6]]
Массив из нулей: [0. 0. 0. 0. 0.]
Массив 3x4 из единиц:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Массив с arange: [0 2 4 6 8]


In [2]:
print("\n--- Атрибуты массива ---")
print("Форма array_2d:", array_2d.shape)
print("Тип данных array_2d:", array_2d.dtype)
print("Размерность array_2d:", array_2d.ndim)


--- Атрибуты массива ---
Форма array_2d: (2, 3)
Тип данных array_2d: int64
Размерность array_2d: 2


In [3]:
demo_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print("Исходный массив:", demo_array)
print("Элемент с индексом 0:", demo_array[0])
print("Элемент с индексом 4:", demo_array[4])
print("Срез [2:6]:", demo_array[2:6])

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Двумерный массив:")
print(matrix)
print("Элемент [1,2]:", matrix[1, 2])
print("Срез первых двух строк:", matrix[:2])

Исходный массив: [10 20 30 40 50 60 70 80 90]
Элемент с индексом 0: 10
Элемент с индексом 4: 50
Срез [2:6]: [30 40 50 60]
Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент [1,2]: 6
Срез первых двух строк: [[1 2 3]
 [4 5 6]]


In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print("arr1:", arr1)
print("arr2:", arr2)
print("Поэлементное сложение:", arr1 + arr2)
print("Поэлементное умножение:", arr1 * arr2)

print("\n--- Статистика ---")
print("Среднее значение:", np.mean(arr1))
print("Сумма элементов:", np.sum(arr1))
print("Минимальное значение:", np.min(arr1))
print("Максимальное значение:", np.max(arr1))

data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Среднее по всем элементам:", np.mean(data_2d))

arr1: [1 2 3 4 5]
arr2: [10 20 30 40 50]
Поэлементное сложение: [11 22 33 44 55]
Поэлементное умножение: [ 10  40  90 160 250]

--- Статистика ---
Среднее значение: 3.0
Сумма элементов: 15
Минимальное значение: 1
Максимальное значение: 5
Среднее по всем элементам: 5.0
